[package]
name = "libvctrl_plumbing"
version = "0.2.0"
edition = "2024"
description = "Plumbing commands for the libvctrl version control system"
license = "MIT"
authors = ["mroczect"]
repository = "https://github.com/mroczect/libvctrl"
homepage = "https://github.com/mroczect/libvctrl"
documentation = "https://docs.rs/libvctrl"
readme = "README.md"
keywords = ["version-control", "vcs", "plumbing"]
categories = ["development-tools"]

[dependencies]
libvctrl = { path = "../libvctrl", version = "2.1.3" }

[dev-dependencies]
libvctrl_core = { path = "../libvctrl_core", version = "3.0.0" }

[lints]
workspace = true
