title: "libvctrl"
description: "Content-Addressed Version Control Framework"
url: "https://mroczect.biz.id"
baseurl: ""
markdown: kramdown
theme: jekyll-theme-cayman
exclude:
  - Cargo.toml
  - Cargo.lock
  - target/
  - .github/
  - src/
  - libvctrl_handler/
  - libvctrl_core/
  - libvctrl_plumbing/
  - libvctrl_porcelain/
