[workspace]
resolver = "2"
members = ["libvctrl","libvctrl_core","libvctrl_handler", "libvctrl_plumbing", "libvctrl_porcelain", "libvctrl_sha512"]

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "MIT"
authors = ["mroczect"]
repository = "https://github.com/mroczect/libvctrl"
homepage = "https://github.com/mroczect/libvctrl"
documentation = "https://docs.rs/libvctrl"
keywords = ["git", "vcs", "cryptography", "sha512", "no-std"]
categories = ["development-tools", "cryptography", "algorithms", "no-std"]

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"
dead_code = "deny"
unused_imports = "deny"
unused_variables = "deny"
unused_lifetimes = "deny"
unused_macro_rules = "deny"
unused_crate_dependencies = "deny"
unreachable_pub = "deny"
rust_2018_idioms = { level = "deny", priority = -1 }
elided_lifetimes_in_paths = "deny"
explicit_outlives_requirements = "deny"
non_ascii_idents = "deny"
trivial_bounds = "deny"
unit_bindings = "deny"
macro_use_extern_crate = "forbid"
single_use_lifetimes = "warn"
redundant_lifetimes = "deny"
rust_2021_compatibility = { level = "warn", priority = -1 }
rust_2024_compatibility = { level = "warn", priority = -1 }
unused_qualifications = "deny"
noop_method_call = "deny"
unnameable_types = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }

todo = "deny"
unimplemented = "deny"
unreachable = "deny"

unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
indexing_slicing = "warn"
map_err_ignore = "warn"
wildcard_enum_match_arm = "warn"
needless_return = "warn"
match_same_arms = "warn"
std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"
doc_markdown = "warn"
doc_lazy_continuation = "warn"
uninlined_format_args = "warn"
