[package]
name = "libvctrl_handler"
version = "5.0.0"
edition = "2024"
description = "Fundamental contracts for building a version control system – no implementations, only traits and types"
license = "MIT"
authors = ["mroczect"]
documentation = "https://docs.rs/libvctrl"
homepage = "https://github.com/mroczect/libvctrl"
repository = "https://github.com/mroczect/libvctrl"
readme = "README.md"
keywords = ["version-control", "vcs", "library", "traits"]
categories = ["development-tools", "data-structures"]

[lints]
workspace = true